services:
  db:
    container_name: CNWeb
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: MyStrong!Passw0rd
      ACCEPT_EULA: "Y"
    ports:
      - "1434:1433"
    volumes:
      - cnweb_data:/var/lib/mssql/cnweb_data

volumes:
  cnweb_data:
    driver: local